route:
  name: north_inspection
  default_altitude_m: 1
  default_hover_s: 2.0

  steps:      

    - name: A
      position: [2, 0.0, 1.0]
      hover_s: 2.0
      yaw_deg: 180
      inspect: false


    - name: B_arrival
      position: [2, 4, 1.0]
      yaw_deg: 180
      inspect: false
      hover_s: 5.0          


    - name: BC_arrival # distance of 0.8
      position: [0.8, 4, 1.5]
      yaw_deg: 180
      inspect: false
      hover_s: 15.0

    - name: BC_photo
      position: [0.8, 4, 1.5]
      yaw_deg: 180
      inspect: true
      action: snapshot


    - name: BC_arrival_down # distance of 0.8
      position: [0.8, 4, 0.5]
      yaw_deg: 180
      inspect: false
      hover_s: 15.0

    - name: BC_photo_down
      position: [0.8, 4, 0.5]
      yaw_deg: 180
      inspect: true
      action: snapshot

    - name: C_arrival_down
      position: [0.0, 4, 0.5]
      yaw_deg: 180
      inspect: false
      hover_s: 15.0

    - name: C_photo_down
      position: [0.0, 4, 0.5]
      yaw_deg: 180
      inspect: true
      action: snapshot

    - name: C_arrival
      position: [0.0, 4, 1.5]
      yaw_deg: 180
      inspect: false
      hover_s: 15.0

    - name: C_photo
      position: [0.0, 4, 1.5]
      yaw_deg: 180
      inspect: true
      action: snapshot

    - name: CD_arrival
      position: [-0.8, 4, 1.5]
      yaw_deg: 180
      inspect: false
      hover_s: 15.0

    - name: CD_photo
      position: [-0.8, 4, 1.5]
      yaw_deg: 180
      inspect: true
      action: snapshot

    - name: CD_arrival_down
      position: [-0.8, 4, 0.5]
      yaw_deg: 180
      inspect: false
      hover_s: 15.0

    - name: CD_photo_down
      position: [-0.8, 4, 0.5]
      yaw_deg: 180
      inspect: true
      action: snapshot

    - name: D
      position: [-2, 4, 1.5]
      yaw_deg: 180
      inspect: true

    - name: H
      position: [-3, 1.5, 1.5]
      yaw_deg: 180
      inspect: false
