api_version: 1

route_file: routes/drone2_shelf_south.yaml

inspection:
  enable: true

fallback:
  battery_warning: ["return_home"]
  battery_critical: ["land"]

return_home_and_land_on_finish: true
