api_version: 1

route_file: routes/overrack_default.yaml

inspection:
  enable: true
  timeout_s: 4.0

fallback:
  battery_warning: ["return_home"]
  battery_critical: ["land"]

return_home_and_land_on_finish: false
